// <auto-generated />
using System;
using Fourteen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fourteen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420173336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fourteen.Domain.Aggregates.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("age_group");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("country_id");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_name");

                    b.Property<double>("CountryProbability")
                        .HasColumnType("float")
                        .HasColumnName("country_probability");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("gender");

                    b.Property<double>("GenderProbability")
                        .HasColumnType("float")
                        .HasColumnName("gender_probability");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Age");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GenderProbability");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("AgeGroup", "CreatedAt");

                    b.HasIndex("CountryId", "CreatedAt");

                    b.HasIndex("Gender", "CreatedAt");

                    b.ToTable("profiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
